name: Testing via Karma
run-name: Running tests...
on: [ push ]
jobs:
  TestFrontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
      - name: Perform Checks
        run: |
          yarn install
          yarn test --watch=false
        working-directory: frontend
      - run: echo "${{ job.status }}."
